# Don't print a new line at the start of the prompt
add_newline = false

# Prompt order (to place custom commands)
format = """\
  $username\
  ${custom.sudo}\
  $hostname\
  $kubernetes\
  $directory\
  $git_branch\
  $git_commit\
  $git_state\
  $git_status\
  $hg_branch\
  $docker_context\
  $package\
  $dotnet\
  $elixir\
  $elm\
  $golang\
  $haskell\
  $java\
  $julia\
  $nodejs\
  $php\
  $python\
  $ruby\
  $rust\
  $terraform\
  $nix_shell\
  $conda\
  $memory_usage\
  $aws\
  $env_var\
  $crystal\
  $cmd_duration\
  $custom\
  $line_break\
  $jobs\
  $battery\
  $time $character\
"""

[character]
success_symbol = '[\[I\]](bold green) ➜'
error_symbol = '[\[I\]](bold red) ➜'
vicmd_symbol = '[\[N\]](bold green) ➜'

[cmd_duration]
min_time = 0
show_milliseconds = true
format = "[$duration]($style)"

[time]
disabled = false
time_format = "%T"
format = "[$time]($style)"

[golang]
symbol = "go "

[rust]
symbol = "rs "

[python]
symbol = "py "

[nodejs]
symbol = "node "

[package]
symbol = ""

[custom.sudo]
command = "echo sudo"
when = "sudo -n true"
style = "bold fg:#ffb05b"
format = "\\([$output]($style)\\) "
